"""Create inventory table

Revision ID: 813580dee35a
Revises: f5d63feda5a8
Create Date: 2024-05-30 18:22:40.528879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '813580dee35a'
down_revision = 'f5d63feda5a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('study_guide_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['study_guide_id'], ['study_guide.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    # ### end Alembic commands ###
