"""Initial migration

Revision ID: 84e6a5a50a4f
Revises: 
Create Date: 2024-05-22 15:29:11.775826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e6a5a50a4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_study_guide',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Class', sa.String(length=20), nullable=False),
    sa.Column('UnitTopic', sa.String(length=20), nullable=False),
    sa.Column('Price', sa.Integer(), nullable=False),
    sa.Column('Creator', sa.String(length=20), nullable=False),
    sa.Column('Link', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_guide',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Class', sa.String(length=20), nullable=False),
    sa.Column('UnitTopic', sa.String(length=20), nullable=False),
    sa.Column('Price', sa.Integer(), nullable=False),
    sa.Column('Creator', sa.String(length=20), nullable=False),
    sa.Column('Link', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('wallet', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('study_guide')
    op.drop_table('pending_study_guide')
    # ### end Alembic commands ###
